name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: DaveG40/dotnettemplate:latest
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: 1d227ec3-10af-4b4b-b80c-859974847f76
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: 1d227ec3-10af-4b4b-b80c-859974847f76
      run: heroku container:push -a module8subals web
    - name: Release
      env:
        HEROKU_API_KEY: 1d227ec3-10af-4b4b-b80c-859974847f76
      run: heroku container:release -a module8subals web
